name: qinayacloudpro
version: '1.0.2'
summary: Qinaya Cloud Pro
description: |
  Qinaya Cloud Pro

grade: stable
confinement: strict

apps:
  qinayacloudpro:
    command: qinayacloudpro
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - wayland

parts:
  qinayacloudpro:
    plugin: nil
    stage-packages:
      - libnss3
      - libxss1
    source: .
    override-build: |
      snapcraftctl build
    build-packages:
      - electron-builder
    after: [desktop-legacy]
