name: qinayacloudpro
version: '1.0.4'
summary: Qinaya Cloud Pro
description: |
  Qinaya Cloud Pro

base: core22
confinement: strict
grade: stable
compression: lzo


apps:
  qinayacloudpro:
    command: qinayacloudpro --no-sandbox
    extensions: [gnome]
    environment:
      TMPDIR: ${XDG_RUNTIME_DIR}
      PATH: ${SNAP}/bin:${PATH}
    plugs:
      - ubuntu-frame
      - browser-support
      - network
      - network-bind
      - password-manager-service
      - audio-playback

parts:
  qinayacloudpro:
    plugin: nil
    source: .
    override-build: |
        npm install
        npm run build
        mkdir ${CRAFT_PART_INSTALL}/opt -p
        cp -r dist/*unpacked ${CRAFT_PART_INSTALL}/opt/qinayacloudpro
    build-snaps:
    - node/20/stable
    build-packages:
    - unzip
    - libsecret-1-dev
    stage-packages:
    - libnss3
    - libnspr4
