name: qinayacloudpro
version: '1.0.4'
summary: Qinaya Cloud Pro
description: |
  Qinaya Cloud Pro

base: core22
confinement: strict
grade: stable


apps:
  qinayacloudpro:
    command: qinayacloudpro
    plugs:
      - ubuntu-frame
      - browser-support
      - network
      - network-bind

parts:
  qinayacloudpro:
    plugin: nil
    source: .
    override-build: |
        npm install
        npm run snapcraft
    build-snaps:
    - node/20/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4
